### ISSUE TITLE
crash during peakfit

### ISSUE THREAD

**Issue by jwuttke** [scgmlz/Steca#298]
addFiles
fdia select /home/jwu/AA/Quarz/Scan2theta/m249020.dat;/home/jwu/AA/Quarz/Scan2theta/m249021.dat;/home/jwu/AA/Quarz/Scan2theta/m249022.dat;/home/jwu/AA/Quarz/Scan2theta/m249023.dat;/home/jwu/AA/Quarz/Scan2theta/m249024.dat;/home/jwu/AA/Quarz/Scan2theta/m249025.dat
@accept fdia
setupTabs 1 # Baseline
dfgram add 28.9 29.35
dfgram add 33.9 34.25
setupTabs 2 # Peakfits
dfgram add 30.2 31.3
mainTabs 4 # Polefig

=> terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6621535 in __GI_abort () at abort.c:79
#2  0x00007ffff69e9983 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff69ef8c6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff69ef901 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff69efb34 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff69eb86b in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7f568dc in std::map<QString, QVariant, std::less<QString>, std::allocator<std::pair<QString const, QVariant> > >::at (this=0x555555995f10, 
    __k=...) at /usr/include/c++/8/bits/stl_map.h:548
#8  0x00007ffff7f56b97 in Mapped::get<deg> (this=0x555555995f10, key=...)
    at /G/sw/Steca/core/typ/mapped.h:48
#9  0x00007ffff7e2e3ea in PeakFunction::fromFit (name=..., curve=..., 
    rawOutcome=...) at /G/sw/Steca/core/peakfit/peak_function.cpp:54
#10 0x00007ffff7e0c095 in (anonymous namespace)::computePeakFit (jP=0, 
    parent=0x5555556bea20) at /G/sw/Steca/core/data/dfgram.cpp:65
#11 0x00007ffff7e0c358 in Dfgram::<lambda(int, const Dfgram*)>::operator()(int, const Dfgram *) const (__closure=0x5555556beb78, jP=0, parent=0x5555556bea20)
    at /G/sw/Steca/core/data/dfgram.cpp:97
#12 0x00007ffff7e0cfec in std::_Function_handler<Fitted(int, const Dfgram*), Dfgram::Dfgram(Curve&&)::<lambda(int, const Dfgram*)> >::_M_invoke(const std::_Any_data &, int &&, const Dfgram *&&) (__functor=..., __args#0=@0x7fffffffad2c: 0, 
    __args#1=@0x7fffffffad20: 0x5555556bea20)
    at /usr/include/c++/8/bits/std_function.h:283
#13 0x00007ffff7f581d3 in std::function<Fitted (int, Dfgram const*)>::operator()(int, Dfgram const*) const (this=0x5555556beb78, __args#0=0, 
    __args#1=0x5555556bea20) at /usr/include/c++/8/bits/std_function.h:687
#14 0x00007ffff7f57544 in lazy_data::VectorCache<Fitted, Dfgram const*>::check_size(Dfgram const*) const::{lambda(Dfgram const*)#1}::operator()(Dfgram const*) const (this=0x5555556beb40, args#0=0x5555556bea20)
    at /G/sw/Steca/core/typ/lazy_data.h:87
#15 0x00007ffff7f58bf7 in std::_Function_handler<Fitted (Dfgram const*), lazy_data::VectorCache<Fitted, Dfgram const*>::check_size(Dfgram const*) const::{lambda(Dfgram const*)#1}>::_M_invoke(std::_Any_data const&, Dfgram const*&&) (
    __functor=..., __args#0=@0x7fffffffadd8: 0x5555556bea20)
    at /usr/include/c++/8/bits/std_function.h:283
#16 0x00007ffff7f57211 in std::function<Fitted (Dfgram const*)>::operator()(Dfgram const*) const (this=0x555555913938, __args#0=0x5555556bea20)
    at /usr/include/c++/8/bits/std_function.h:687
#17 0x00007ffff7f56a35 in lazy_data::Cached<Fitted, Dfgram const*>::yield (
    this=0x555555913930, args#0=0x5555556bea20)
    at /G/sw/Steca/core/typ/lazy_data.h:41
#18 0x00007ffff7f56b0f in lazy_data::VectorCache<Fitted, Dfgram const*>::yield_at (this=0x5555556beb40, i=0, args#0=0x5555556bea20)
    at /G/sw/Steca/core/typ/lazy_data.h:70
#19 0x00007ffff7f56553 in Dfgram::getPeakFit (this=0x5555556bea20, jP=0)
    at /G/sw/Steca/core/data/dfgram.h:41
#20 0x00007ffff7dd9a1f in (anonymous namespace)::getPeak (jP=0, cluster=..., 
    iGamma=0) at /G/sw/Steca/core/calc/allpeaks_allinfos.cpp:48
#21 0x00007ffff7dd9f1e in (anonymous namespace)::computeDirectInfoSequence (
    jP=0) at /G/sw/Steca/core/calc/allpeaks_allinfos.cpp:71
#22 0x00007ffff7dda07c in AllPeaksAllInfos::<lambda(int, const AllPeaksAllInfos*)>::operator()(int, const AllPeaksAllInfos *) const (__closure=0x7fffffffc518, 
    jP=0) at /G/sw/Steca/core/calc/allpeaks_allinfos.cpp:85
#23 0x00007ffff7ddaae8 in std::_Function_handler<OnePeakAllInfos(int, const AllPeaksAllInfos*), AllPeaksAllInfos::AllPeaksAllInfos()::<lambda(int, const AllPeaksAllInfos*)> >::_M_invoke(const std::_Any_data &, int &&, const AllPeaksAllInfos *&&) (__functor=..., __args#0=@0x7fffffffb15c: 0, 
    __args#1=@0x7fffffffb150: 0x7fffffffc4e0)
    at /usr/include/c++/8/bits/std_function.h:283
#24 0x00007ffff7ddf4d7 in std::function<OnePeakAllInfos (int, AllPeaksAllInfos const*)>::operator()(int, AllPeaksAllInfos const*) const (this=0x7fffffffc518, 
    __args#0=0, __args#1=0x7fffffffc4e0)
    at /usr/include/c++/8/bits/std_function.h:687
#25 0x00007ffff7ddd86e in lazy_data::VectorCache<OnePeakAllInfos, AllPeaksAllInfos const*>::check_size(AllPeaksAllInfos const*) const::{lambda(AllPeaksAllInfos const*)#1}::operator()(AllPeaksAllInfos const*) const (this=0x7fffffffc4e0, 
    args#0=0x7fffffffc4e0) at /G/sw/Steca/core/typ/lazy_data.h:87
#26 0x00007ffff7de1230 in std::_Function_handler<OnePeakAllInfos (AllPeaksAllInfos const*), lazy_data::VectorCache<OnePeakAllInfos, AllPeaksAllInfos const*>::check_size(AllPeaksAllInfos const*) const::{lambda(AllPeaksAllInfos const*)#1}>::_M_invoke(std::_Any_data const&, AllPeaksAllInfos const*&&) (__functor=..., 
    __args#0=@0x7fffffffb208: 0x7fffffffc4e0)
    at /usr/include/c++/8/bits/std_function.h:283
#27 0x00007ffff7ddddfd in std::function<OnePeakAllInfos (AllPeaksAllInfos const*)>::operator()(AllPeaksAllInfos const*) const (this=0x5555559d4968, 
    __args#0=0x7fffffffc4e0) at /usr/include/c++/8/bits/std_function.h:687
#28 0x00007ffff7ddc50b in lazy_data::Cached<OnePeakAllInfos, AllPeaksAllInfos const*>::yield (this=0x5555559d4960, args#0=0x7fffffffc4e0)
    at /G/sw/Steca/core/typ/lazy_data.h:41
#29 0x00007ffff7ddc22f in lazy_data::VectorCache<OnePeakAllInfos, AllPeaksAllInfos const*>::yield_at (this=0x7fffffffc4e0, i=0, args#0=0x7fffffffc4e0)
    at /G/sw/Steca/core/typ/lazy_data.h:70
#30 0x00007ffff7dda37b in AllPeaksAllInfos::currentDirect (this=0x7fffffffc4e0)
    at /G/sw/Steca/core/calc/allpeaks_allinfos.cpp:114
#31 0x00007ffff7dda4a8 in AllPeaksAllInfos::currentInfoSequence (
    this=0x7fffffffc4e0) at /G/sw/Steca/core/calc/allpeaks_allinfos.cpp:128
#32 0x00007ffff7f7ed0d in (anonymous namespace)::computePoints (flat=false, 
    withHighlight=true) at /G/sw/Steca/gui/view/plot_polefig.cpp:25
#33 0x00007ffff7f7fb5f in PlotPolefig::<lambda()>::operator()(void) const (
    __closure=0x555555980878) at /G/sw/Steca/gui/view/plot_polefig.cpp:121
#34 0x00007ffff7f7ff7d in std::_Function_handler<void(), PlotPolefig::PlotPolefig(bool)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/8/bits/std_function.h:297
#35 0x00007ffff7cd7310 in std::function<void ()>::operator()() const (
    this=0x555555980878) at /usr/include/c++/8/bits/std_function.h:687
#36 0x00007ffff7cd68eb in QcrBase::remake (this=0x555555980870)
    at /G/sw/Steca/qcr/engine/mixin.cpp:41
#37 0x00007ffff7cd6b74 in QcrRoot::remakeAll (this=0x555555652240)
    at /G/sw/Steca/qcr/engine/mixin.cpp:68
#38 0x00007ffff7ce299a in QcrSingleValue<int>::onChangedValue (
    this=0x55555594be40, val=4, comment=...)
    at /G/sw/Steca/qcr/engine/single_value.h:133
#39 0x00007ffff7cdf825 in QcrTabWidget::<lambda(int)>::operator()(int) const (
    __closure=0x555555991d90, val=4)
    at /G/sw/Steca/qcr/widgets/controls.cpp:269
#40 0x00007ffff7ce1a74 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<int>, void, QcrTabWidget::QcrTabWidget(const QString&)::<lambda(int)> >::call(QcrTabWidget::<lambda(int)> &, void **) (f=..., arg=0x7fffffffb8e0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:128
#41 0x00007ffff7ce176e in QtPrivate::Functor<QcrTabWidget::QcrTabWidget(const QString&)::<lambda(int)>, 1>::call<QtPrivate::List<int>, void>(QcrTabWidget::<lambda(int)> &, void *, void **) (f=..., arg=0x7fffffffb8e0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:238
#42 0x00007ffff7ce156e in QtPrivate::QFunctorSlotObject<QcrTabWidget::QcrTabWidget(const QString&)::<lambda(int)>, 1, QtPrivate::List<int>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, 
    this_=0x555555991d80, r=0x55555594be80, a=0x7fffffffb8e0, ret=0x0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:421
#43 0x00007ffff6d74a43 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00007ffff78868be in QTabWidget::currentChanged(int) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007ffff7888c9f in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007ffff6d74906 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007ffff7867cfe in QTabBar::currentChanged(int) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007ffff786c2fd in QTabBar::setCurrentIndex(int) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007ffff7cdfa1a in QcrTabWidget::setCurrentIndex (this=0x55555594be40, 
    val=4) at /G/sw/Steca/qcr/widgets/controls.cpp:290
#50 0x00007ffff7f5bb4c in QcrTabWidget::doSetValue (this=0x55555594be40, val=4)
    at /G/sw/Steca/qcr/widgets/controls.h:149
#51 0x00007ffff7f5c12a in QcrSingleValue<int>::setFromCommand (
    this=0x55555594be40, arg=...) at /G/sw/Steca/qcr/engine/single_value.h:111
#52 0x00007ffff7cacad3 in Console::wrappedCommand (this=0x7fffffffd5f0, 
    line=...) at /G/sw/Steca/qcr/engine/console.cpp:238
#53 0x00007ffff7cac349 in Console::commandsFromStack (this=0x7fffffffd5f0)
    at /G/sw/Steca/qcr/engine/console.cpp:169
#54 0x00007ffff7cac17c in Console::runScript (this=0x7fffffffd5f0, fName=...)
    at /G/sw/Steca/qcr/engine/console.cpp:157
#55 0x00007ffff7f472c3 in MainWin::<lambda()>::operator()(void) const (
    __closure=0x555555ab0040) at /G/sw/Steca/gui/mainwin.cpp:98
#56 0x00007ffff7f49971 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, MainWin::MainWin(const QString&)::<lambda()> >::call(MainWin::<lambda()> &, void **) (f=..., arg=0x7fffffffbec0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:128
#57 0x00007ffff7f49952 in QtPrivate::Functor<MainWin::MainWin(const QString&)::<lambda()>, 0>::call<QtPrivate::List<>, void>(MainWin::<lambda()> &, void *, void **) (f=..., arg=0x7fffffffbec0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:238
#58 0x00007ffff7f49920 in QtPrivate::QFunctorSlotObject<MainWin::MainWin(const QString&)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x555555ab0030, 
    r=0x7fffffffd6d0, a=0x7fffffffbec0, ret=0x0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:421
#59 0x00007ffff6d80556 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00007ffff6d7513b in QObject::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#61 0x00007ffff76c84b1 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007ffff76cf950 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007ffff6d4b5a9 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#64 0x00007ffff6d9bc78 in QTimerInfoList::activateTimers() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#65 0x00007ffff6d9c4d4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#66 0x00007ffff5475f2e in g_main_context_dispatch ()
   from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#67 0x00007ffff54761c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#68 0x00007ffff547625c in g_main_context_iteration ()
   from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#69 0x00007ffff6d9c863 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#70 0x00007ffff1b7a3e1 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#71 0x00007ffff6d4a27b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#72 0x00007ffff6d52262 in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#73 0x000055555556c399 in main (argc=2, argv=0x7fffffffe098)
    at /G/sw/Steca/main/steca.cpp:139

**Comment by jwuttke** [comment]
seems solved, cannot reproduce failure
